import Head from "next/head";
import styles from "../styles/AboutMe.module.css";

const AboutMe = () => {
  return (
    <>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/profile-pic.png" />
      </Head>
      <div className={styles.body}>
        <div className={styles.container}>
          <div className={styles.avatar}>
            <img src={"./profile-pic.png"} alt="Noor" />
          </div>
          <div className={styles.username}>
            <h3>Noor Ul Amin</h3>
          </div>
          <div className={styles.button} data-target="#home">
            <div className={styles.button__icon}></div>
            <div className={styles.button__text}>Home</div>
          </div>
          <div className={styles.button} data-target="#contact">
            <div className={styles.button__icon}></div>
            <div className={styles.button__text}>Contact</div>
          </div>
          <div className={styles.button} data-target="#about">
            <div className={styles.button__icon}></div>
            <div className={styles.button__text}>About</div>
          </div>
          <div className={styles.button} data-target="#education">
            <div className={styles.button__icon}></div>
            <div className={styles.button__text}>Education</div>
          </div>
        </div>
        <div className={styles.page} id="home">
          <div className={styles.page__header}>
            <div className={styles.page__title}>Home</div>
            <div className={styles.page__close}></div>
          </div>
          <div className={styles.page__body}></div>
        </div>
        <div className={styles.page} id="contact">
          <div className={styles.page__header}>
            <div className={styles.page__title}>Contact</div>
            <div className={styles.page__close}></div>
          </div>
          <div className={styles.page__body}></div>
        </div>
        <div className={styles.page} id="about">
          <div className={styles.page__header}>
            <div className={styles.page__title}>About</div>
            <div className={styles.page__close}></div>
          </div>
          <div className={styles.page__body}></div>
        </div>
        <div className={styles.page} id="education">
          <div className={styles.page__header}>
            <div className={styles.page__title}>Education</div>
            <div className={styles.page__close}></div>
          </div>
          <div className={styles.page__body}></div>
        </div>
      </div>
    </>
  );
};

export default AboutMe;
